### ISSUE TITLE
i have some problem.

### ISSUE THREAD

**Issue by byeongcheoljo** [QuyAnh2005/vits-japanese#3]
`torch.LongTensor([x[1].size(1) for x in batch]),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

what can i do....?

**Comment by QuyAnh2005** [comment]
@byeongcheoljo Double-check that the `/path/to/dataset/wavs`, folder contains wav files `only`. Any other file types will cause an out of range error.

**Comment by byeongcheoljo** [comment]
@QuyAnh2005  Thank you. I solved this problem.

Do you have any generate audio file  result?

**Comment by Jimvc** [comment]
> [@QuyAnh2005](https://github.com/QuyAnh2005) Thank you. I solved this problem.
> 
> Do you have any generate audio file result?
Hello,[byeongcheoljo](https://github.com/byeongcheoljo).How did  fix it?
Once I run train.py,
\jp_dataset\basic5000\wav generates the .spec.pt file.
Thank you.
